# Generated by Django 4.1.1 on 2022-10-12 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 13, 56, 15, 443384)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='month',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='day',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 13, 56, 15, 443384)),
        ),
    ]
