# Generated by Django 4.1.1 on 2022-10-12 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimeapp', '0002_alter_customuser_date_joined_alter_profile_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 15, 24, 32, 107718)),
        ),
        migrations.AlterField(
            model_name='organization',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 12, 15, 24, 32, 107718)),
        ),
    ]
