# Generated by Django 4.1.1 on 2022-10-12 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimeapp', '0003_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 15, 40, 41, 450057)),
        ),
        migrations.AlterField(
            model_name='time',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 15, 40, 41, 450057)),
        ),
    ]
